services:
  - type: web
    name: aq-monitor
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aq-monitor-db
          property: connectionString

databases:
  - name: aq-monitor-db
